### ISSUE TITLE
Terraform destroy hangs if you run it with a running ClickHouse cluster

### ISSUE THREAD

**Issue by hodgesrm** [Altinity/terraform-aws-eks-clickhouse#2]
Terraform destroy times out in some cases. It looks as if it occurs if you try to delete the EKS cluster when there's a running load balancer. The symptom is that the destroy fails with a message like the following: 
```
module.eks_clickhouse.module.eks.aws_subnet.this[2]: Still destroying... [id=subnet-0d6aebbcb23be5d80, 20m0s elapsed]
module.eks_clickhouse.module.eks.aws_subnet.this[0]: Still destroying... [id=subnet-0dba6e3ede1bb6b2c, 20m0s elapsed]
module.eks_clickhouse.module.eks.aws_subnet.this[1]: Still destroying... [id=subnet-0c42cdcca0dfe95ee, 20m0s elapsed]
╷
│ Error: deleting EC2 Internet Gateway (igw-020544033515202ab): detaching EC2 Internet Gateway (igw-020544033515202ab) from VPC (vpc-0e56a9cd7eb13000d): DependencyViolation: Network vpc-0e56a9cd7eb13000d has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
│       status code: 400, request id: b8a528c3-d9cb-4b58-8c8d-bdc91d93a5c4
│
│
```
At this point only the Internet Gateway, subnets, and VPC remain. 

It appears that a load balancer is being created as a side effect of bringing up the ClickHouse cluster. You find the load balancer and delete it. However there also appear to be network interfaces attached to the subnets that have IPV4 public IPs, possibly as a side effect of creating the load balancer. You can find the interfaces by going to the EC2 network interfaces screen and looking for ENIs that have your VPC id, e.g., vpc-0e56a9cd7eb13000d.  Trying to delete them results in the following error: 

```
Failed to detach 3 network interfaces
Details
eni-0f614cae2faeef5c5 - API error: "You do not have permission to access the specified resource."
eni-0232650ba41cb8d1a - API error: "You do not have permission to access the specified resource."
eni-046a163ed4f863e23 - API error: "You do not have permission to access the specified resource."
```

As a result you are stuck and cannot complete the destroy operation.

**Comment by hodgesrm** [comment]
The workaround: Delete any ClickHouse cluster before running `terraform destroy`.

Longer term solution: don't create an external load balancer. This also eliminates issues with security due to having a public port.

**Comment by ianaya89** [comment]
Resolved https://github.com/Altinity/terraform-aws-eks-clickhouse/commit/18402cb9bf223c51b2d95a0f48019b27718945fb
