### ISSUE TITLE
Terraform apply fails intermittently when running manifest for clickhouse-operator

### ISSUE THREAD

**Issue by hodgesrm** [Altinity/terraform-aws-eks-clickhouse#4]
Terraform apply fails intermittently on the EKS blueprint when it get to the stage of loading manifests. Here's the error: 
```
20f"]: Creating...
module.eks_clickhouse.module.clickhouse_operator.kubectl_manifest.clickhouse_operator["36c0bcf4404dce96562ca9415262f4828a6c355c"]: Creating...
module.eks_clickhouse.module.clickhouse_operator.kubectl_manifest.zookeeper_cluster["8d0b835ecbf604bfa13f334f17429e914ef426f5"]: Creating...
module.eks_clickhouse.module.clickhouse_operator.kubectl_manifest.zookeeper_cluster["9e2ef57f98412640af3d162ccba5cb7b3402f27e"]: Creating...
module.eks_clickhouse.module.clickhouse_operator.kubectl_manifest.zookeeper_cluster["66b8c62c5f1e4e177711f2ba7c1cbc968f24fcdf"]: Creating...
module.eks_clickhouse.module.clickhouse_operator.kubectl_manifest.zookeeper_cluster["81f9379b0f5e802403435894346a545fb3e01ac8"]: Creating...
╷
│ Error: kube-system/etc-clickhouse-operator-confd-files failed to create kubernetes rest client for update of resource: Get "http://localhost/api?timeout=32s": dial tcp 127.0.0.1:80: connect: connection refused
│
│   with module.eks_clickhouse.module.clickhouse_operator.kubectl_manifest.clickhouse_operator["56b5c91cdf512ac011eba70162b387577dd6889f"],
│   on .terraform/modules/eks_clickhouse/clickhouse-operator/main.tf line 11, in resource "kubectl_manifest" "clickhouse_operator":
│   11: resource "kubectl_manifest" "clickhouse_operator" {
│
╵
```
Rerunning circa 10 minutes later works, which makes it seem that the K8s cluster is somehow not ready. Note that when running the second time there is no output, so I can't get the ClickHouse user password or other information. 

The eks-cluster.tf file that reproduces this problem is attached. 

[eks-cluster.tf.txt](https://github.com/Altinity/terraform-aws-eks-clickhouse/files/14470372/eks-cluster.tf.txt)

**Comment by hodgesrm** [comment]
Definitely an intermittent failure. A second run succeeded.

**Comment by ianaya89** [comment]
It's curious that tries to reach k8s cluster on `"http://localhost/api?timeout=32s"`, looks like the provider is fails to obtain generated kubeconfig settings

**Comment by denisok** [comment]
I might triggered it as well. Attaching debug logs with errors for `terraform destroy`
[tf.log](https://github.com/Altinity/terraform-aws-eks-clickhouse/files/14483785/tf.log)

**Comment by ianaya89** [comment]
@hodgesrm @denisok I applied some improvements on k8s provider setup. Will get latest changes and make a try

**Comment by ianaya89** [comment]
@denisok @hodgesrm added some improvements that should fix this issue. Please get latest changes and test it
